spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: your-256-bit-secret-key-must-be-at-least-32-chars-long
  expiration: 86400000

server:
  port: 8080